---
language: node_js
node_js:
  - node
cache: yarn
script:
  - yarn lint
  - yarn test
notifications:
  email: false
  slack:
    secure: PDMS6481l4Brm/OzwvrGc6NsPoIUyTSV5hJdXp9ztCsEde9ZmTPwKQycjiv2ZS+Dw4wD2UoJvbuJBLfk7Up9y9QJYYxajwoSeVQbfO/m2aD0OIEolEk36xsZbQ3yY7QgUThE0jbE19LXODIcjqfmfNQPoYTgtY84avqRCAnfthP0EoZ0lQqmagNvTjWAAH+/6GVJvq1bbiYkb88p0iMO/9TEA3796LVfrPzPH/hV64uywz5tBUYeOVN1C1VUiE/ilarZnCFF5bNBchkEOTNkOEkN0gosO74TfHU+2iAjoaYYdQ6N5AtGo5NAoKC/Mz7/PKlgWHD3WyKr3dVF1OyHX1I/v+hYepnKZpqB6++USLZmq78xQ0GFfGYnAJDuzKceVT1qrdyB6nbCoBm17Ixy+yy++Z8qt7/BtfPtijEFeJPJ2+bXOo9+kHV9ZPwW1d1AduwK9Bm0ACWlauVxuFDJpiOKMzrPbEHhickmUmkJGXKWz1sAzeZbRSfajXg2KpRzq6djHYTap+LnZUvHZSO3I33vq+DOOoPilRqR3IEK5yvFcXlRvEow8HOAXOFncl4e4gvE/dR8lhygcKUseEcgV1Ub2UwbXJ2457T6ON3ZZ2r2mUbiX9lfMlwqevsfPH/bW/nYFTFjjx9pfIB88+/z2SB9ZJ3sZ8INUeZSuJe56mc=
